extends Node
class_name AbsurdCardsData

# ============================================
# FUNCOES AUXILIARES
# ============================================

static func get_packs_info() -> Array:
	return [
		{
			"id": "classico",
			"name": "CLÁSSICO",
			"description": "O jogo original. Perguntas e respostas absurdas para destruir amizades.",
			"available": true,
			"black_count": BLACK_CARDS_BR.size(),
			"white_count": WHITE_CARDS_BR.size()
		},
		{
			"id": "insano",
			"name": "INSANO",
			"description": "Para quem acha que o clássico é leve demais. Conteúdo +18 extremo.",
			"available": false, # Em breve
			"black_count": 0,
			"white_count": 0
		},
		{
			"id": "meme",
			"name": "MEMES BR",
			"description": "Um pack focado na cultura da internet brasileira.",
			"available": false, # Em breve
			"black_count": 0,
			"white_count": 0
		}
	]

static func get_black_cards() -> Array:
	# Retorna cartas baseado no idioma (simplificado por enquanto)
	# Idealmente, acessaria LocalizationManager, mas como é estático,
	# vamos checar se existe a classe global ou usar padrao
	return BLACK_CARDS_BR.duplicate()

static func get_white_cards() -> Array:
	return WHITE_CARDS_BR.duplicate()

# ============================================
# INSTRUCOES DE PREENCHIMENTO
# ============================================
# Substitua os exemplos abaixo com as cartas reais.
# Mantenha o formato de string entre aspas.
# Para cartas pretas (perguntas), use "____" para indicar o espaco em branco.

# ============================================
# CARTAS BRASILEIRAS (PT-BR EXCLUSIVO)
# ============================================
# Estas cartas aparecem APENAS quando o idioma e Portugues.
const BLACK_CARDS_BR = [
	"Por que eu nao consigo dormir a noite?",
	"Eu tenho 99 problemas, mas ____ nao e um deles.",
	"Qual e o proximo brinquedo do McLanche Feliz?",
	"Papai, por que a mamae esta chorando?",
	"No novo filme da Disney, Hannah Montana luta contra ____.",
	"Em vez de carvao, o Papai Noel agora da ____ para as criancas malcriadas.",
	"Qual e o prazer culposo do Batman?",
	"Cara, isso vai ser o melhor ____ de todos os tempos!",
	"As diretrizes da TSA agora proibem ____ em avioes.",
	"O que acabou com meu ultimo relacionamento?",
	"Guerra! Para que serve?",
	"O que Dick Cheney prefere em vez de afogamento simulado?",
	"____. E assim que eu quero morrer.",
	"Que cheiro e esse?",
	"Eu bebo para esquecer ____.",
	"Novo da Mattel: O acessorio de ____ da Barbie.",
	"O que ajuda Obama a relaxar?",
	"Durante o sexo, eu gosto de pensar em ____.",
	"O que eu trouxe do Mexico?",
	"Quando eu for Primeiro Ministro, criarei o Ministerio de ____.",
	"O que e essa coisa crocante no meu sofa?",
	"A seguir na MTV: Pimp My ____.",
	"Passo 1: ____. Passo 2: ____. Passo 3: Lucro.",
	"Disseram que eramos loucos. Disseram que nao podiamos colocar ____ dentro de ____. Eles estavam errados.",
	"Desculpe pessoal, eu acabei de ____.",
	"A vida dos indigenas mudou para sempre quando o Homem Branco lhes apresentou ____.",
	"O que e a coisa mais emo?",
	"Chegando a Broadway nesta temporada, ____: O Musical.",
	"A excursao da escola foi completamente arruinada por ____.",
	"Em um mundo devastado por ____, nosso unico consolo e ____.",
	"Eu nunca entendi verdadeiramente ____ ate encontrar ____.",
	"Dizem os boatos que o prato favorito de Vladimir Putin e ____.",
	"O que meus pais estao escondendo de mim?",
	"____: Bom ate a ultima gota.",
	"O que o exercito dos EUA lancou de paraquedas para as criancas do Afeganistao?",
	"Do que vou abrir mao na Quaresma?",
	"No novo filme de M. Night Shyamalan, Bruce Willis descobre que na verdade era ____ o tempo todo.",
	"Como eu perdi minha virgindade?",
	"O encontro as cegas estava indo horrivelmente ate descobrirmos nosso amor compartilhado por ____.",
	"____. E uma cilada, Bino!",
	"Um jantar romantico a luz de velas estaria incompleto sem ____.",
	"O Museu de Historia Natural acaba de abrir uma exposicao interativa sobre ____.",
	"____. Duvido voce comer um so!",
	"E uma pena que as criancas de hoje estejam se envolvendo com ____.",
	"O que destruiu totalmente o meu cu?",
	"Minha patria amada, terra gentil de ____.",
	"O que me da gases incontrolaveis?",
	"A nova Biblia apresenta um Jesus moderno e descolado que perdoa ____.",
	"Qual e o segredo para um casamento feliz?",
	"Meu professor de educacao fisica foi demitido por adicionar ____ a pista de obstaculos.",
	"O Papa canonizou oficialmente o santo padroeiro de ____.",
	"____. Toca aqui, irmao.",
	"Desculpe, Professor, mas nao consegui terminar meu dever de casa por causa de ____.",
	"Do que o ceu esta cheio?",
	"Pessoas brancas gostam de ____.",
	"Por que estou grudento?",
	"Hoje no Casos de Familia: \"Socorro! Meu filho e ____!\"",
	"____. Testado por criancas, aprovado pelas maes.",
	"Antes de te matar, Sr. Bond, preciso te mostrar ____.",
	"Qual e a nova dieta da moda?",
	"A Liga Principal de Beisebol baniu ____ por dar aos jogadores uma vantagem injusta.",
	"Se Deus nao quisesse que desfrutassemos de ____, ele nao nos teria dado ____.",
	"Nao sei com que armas a III Guerra Mundial sera lutada, mas a IV Guerra Mundial sera lutada com ____.",
	"Qual e o presente que nunca acaba?",
	"No principio havia ____. E o Senhor disse: \"Haja ____.\"",
	"Novo da Pfizer: Viagra para ____.",
	"O processo de cura comecou quando entrei para um grupo de apoio a vitimas de ____.",
	"O Exorcismo de Emily Rose foi na verdade causado por ____.",
	"Qual e a pior coisa que voce pode encontrar em um buffet de comida chinesa?",
	"____. O cafe da manha dos campeoes.",
	"Quando eu estiver na prisao, vou esconder ____ na minha cavidade anal.",
	"A internet serve para ____.",
	"Contemplem os Quatro Cavaleiros do Apocalipse! Guerra, Fome, Pestilencia e ____.",
	"Para produzir a erecao perfeita, voce deve usar ____.",
	"O que me faz vomitar em jato?",
	"A ciencia nunca explicara a origem de ____.",
	"Durante sua crise de meia-idade, meu pai comecou a curtir ____.",
	"Acorde, America. Os terroristas venceram. Eles tem ____.",
	"Em seus momentos finais, Michael Jackson murmurou sobre ____.",
	"____. E o que tem para o jantar.",
	"Apenas duas coisas na vida sao certas: a morte e ____.",
	"Quem e o homem mais perigoso do mundo?",
	"A CIA esta atualmente monitorando ____.",
	"O que e a coisa mais irritante nos meus colegas de trabalho?",
	"A melhor cantada comeca com ____.",
	"Meu terapeuta diz que tenho uma obsessao doentia por ____.",
	"A profecia previu que o mundo acabaria com ____.",
	"O que esta se escondendo debaixo da minha cama?",
	"Eu finalmente encontrei um uso para ____.",
	"____. Porque eu mereco.",
	"A unica coisa que me deixa de pau duro hoje em dia e ____.",
	"Qual e o fruto proibido definitivo?",
	"Minha autobiografia se chama \"____: Uma Historia de Amor.\"",
	"O Premio Nobel da Paz vai para ____.",
	"O que acontece em Vegas fica em Vegas, exceto ____.",
	"Por que a galinha atravessou a rua?",
	"____. Nem uma vezinha.",
	"Quem soltou os cachorros?",
	"Clique aqui para solteiras gostosas na sua area procurando por ____.",
	"O ingrediente secreto nos biscoitos da Vovo e ____.",
	"O verdadeiro motivo da separação de Fátima e Bonner foi: ____.",
	"O que a Anvisa encontrou na cozinha do MasterChef?",
	"A nova modalidade olímpica do Brasil é ____.",
	"Não há nada mais brasileiro do que ____.",
	"Qual é o segredo para um casamento duradouro?",
	"A manchete do Meia Hora amanhã será: ____.",
	"O que realmente aconteceu no episódio perdido do Sítio do Picapau Amarelo?",
	"Para salvar a audiência, o Fantástico exibiu uma reportagem sobre: ____.",
	"O que o Galvão Bueno grita na hora do orgasmo?",
	"A Xuxa fez um pacto com o Diabo em troca de: ____.",
	"O que tem dentro da mala do Silvio Santos?",
	"O próximo participante da Fazenda é ninguem menos que: ____.",
	"Qual foi a causa da briga no grupo da família no WhatsApp?",
	"O que a Grávida de Taubaté usou para encher a barriga?",
	"A única coisa capaz de parar a Carreta Furacão é ____.",
	"Revelado: O Louro José era, na verdade, controlado por: ____.",
	"O que o Faustão diria se visse meu histórico de navegação? \"Ô louco, bicho! É ____!\"",
	"Qual é o nome do novo hit do Carnaval de Salvador?",
	"A Globo não quer que você saiba, mas o prêmio do Big Brother é ____.",
	"No remake de \"Dona Flor e Seus Dois Maridos\", Vadinho volta como ____.",
	"Minha fantasia sexual envolve algemas, chantilly e ____.",
	"Depois de 5 doses de Catuaba, eu sou capaz de: ____.",
	"O segredo do sexo bom é: ____.",
	"Para minha surpresa, dentro da calça dele encontrei: ____.",
	"O que acabou com o clima na hora H?",
	"Minha mãe chorou quando descobriu meu trabalho: ____.",
	"O Tinder deletou minha conta por causa desta foto: ____.",
	"Amor é passageiro, mas ____ é para sempre.",
	"A primeira vez que transei, usei ____ como lubrificante.",
	"O que as mulheres realmente querem?",
	"Homem de verdade não chora, homem de verdade gosta de: ____.",
	"Qual é a posição sexual favorita dos caminhoneiros?",
	"O que eu escondo debaixo da cama quando trago alguém para casa?",
	"A melhor cura para a solidão é ____.",
	"Minha ex terminou comigo por causa do meu vício: ____.",
	"O que é melhor que sexo oral?",
	"No Kama Sutra brasileiro, a posição 69 foi substituída por: ____.",
	"O apelido carinhoso do meu pênis é ____.",
	"O que fiz no banheiro da balada que me arrependo até hoje?",
	"Antes de beijar, verifique se a pessoa não tem gosto de: ____.",
	"O pastor disse que ____ é coisa do Diabo.",
	"O que me fez ser expulso do velório?",
	"Em caso de emergência, quebre o vidro e use ____.",
	"A fila do SUS estava tão grande que comecei a: ____.",
	"O que vem na Cesta Básica do governo?",
	"O Brasil só vai melhorar quando legalizarem: ____.",
	"A única coisa que funciona no Rio de Janeiro é ____.",
	"O que eu daria para o flanelinha não riscar meu carro: ____.",
	"Minha vida financeira pode ser resumida em uma palavra: ____.",
	"O motorista do Uber me deu 1 estrela porque eu fui pego: ____.",
	"O que não pode faltar no churrasco de domingo na laje?",
	"A polícia apreendeu 50kg de ____ na fronteira.",
	"O motivo do meu nome estar no Serasa é: ____.",
	"Dois caras numa moto perguntaram por: ____.",
	"O que eu compraria se ganhasse na Mega-Sena acumulada?",
	"A reforma tributária vai taxar até ____.",
	"O que está escrito na pichação do muro da escola?",
	"Minha religião me proíbe de comer: ____.",
	"O cheiro do Rio Tietê me lembra: ____.",
	"O que causa mais brigas no transporte público?",
	"O médico disse que a causa da minha morte será: ____.",
	"Qual é o cheiro do inferno?",
	"Deus perdoa tudo, menos ____.",
	"O que o cachorro estava comendo no quintal?",
	"Por que eu estou todo pegajoso?",
	"A pior coisa para se encontrar em um buffet por quilo é ____.",
	"O que sai do meu corpo quando eu espirro muito forte?",
	"Minha avó sempre dizia: \"Quem tem boca vai a ____.\"",
	"O ingrediente secreto da feijoada é ____.",
	"O que eu usaria para limpar a bunda se o papel acabasse?",
	"Qual é a textura da sua alma?",
	"O Diabo veste Prada, mas Jesus veste ____.",
	"O que é mais sujo que pau de galinheiro?",
	"A evolução parou quando o ser humano inventou ____.",
	"O que eu faria por um vale-refeição?",
	"Qual superpoder seria inútil no Brasil?",
	"O que a NASA veria se apontasse o telescópio para o meu quarto?",
	"A verdadeira causa do aquecimento global é: ____.",
	"O que encontraram na autópsia do ET de Varginha?",
	"O que é amarelo, gosmento e canta funk?",
	"Nos livros de história, 2025 será lembrado como o ano de: ____.",
	"O slogan da minha campanha política seria: \"Mais ____, menos corrupção.\"",
	"O que Pedro Álvares Cabral realmente veio procurar no Brasil?",
	"A ditadura militar torturava as pessoas usando: ____.",
	"O que o Lula esconde na barba?",
	"A verdadeira ideologia de gênero é: ____.",
	"O que causou o impeachment da Dilma, segundo o Yahoo Respostas?",
	"O comunismo vai tomar a sua casa e o seu: ____.",
	"O Brasil acima de tudo, ____ acima de todos.",
	"Qual lei deveria ser aprovada no Congresso imediatamente?",
	"O que os políticos fazem em Brasília nas terças-feiras à noite?",
	"A única coisa capaz de unir a esquerda e a direita é: ____.",
	"O que Tiradentes gritou antes de morrer?",
	"A Princesa Isabel assinou a Lei Áurea usando uma caneta feita de: ____.",
	"O que Getúlio Vargas escreveu na carta-testamento, mas apagaram?",
	"O segredo da economia brasileira envolve: ____.",
	"O que a Abin estava monitorando no meu celular?",
	"A reforma da previdência obriga você a trabalhar até: ____.",
	"O que o Movimento Sem Terra realmente quer?",
	"Ordem e ____."
]

const WHITE_CARDS_BR = [
	"Uma buceta dentada.",
	"Piroca latejante.",
	"A fimose do meu pai.",
	"Um dildo de vidro que quebrou lá dentro.",
	"O bilau murcho do seu ex.",
	"Uma estátua de 30 metros de um caralho alado.",
	"A jeba do Kid Bengala.",
	"A benga do asilo.",
	"Polir a bengala do vovô.",
	"Uma perereca úmida e saltitante.",
	"A perereca da vizinha que fugiu da gaiola.",
	"Uma aranha caranguejeira peluda entre as pernas.",
	"Cheiro de bacalhau na feira de domingo.",
	"Molhar o biscoito.",
	"Uma xereca suja.",
	"A caverna da sua mãe.",
	"Estacionar o caminhão na garagem apertada.",
	"O olho do cu piscando.",
	"O botão de rosa.",
	"Rasgar as pregas.",
	"Uma rola de borracha preta.",
	"O clitóris inchado.",
	"Bolas azuis de tanto tesão acumulado.",
	"Um saco escrotal que vai até o joelho.",
	"Mamilos polêmicos.",
	"Um ânus prolapsado parecendo uma rosa vermelha.",
	"Lábios vaginais que batem palmas.",
	"Pêlos pubianos trançados.",
	"A cabeça da rola roxa de asfixia.",
	"Um útero hostil.",
	"Um micropênis com complexo de Napoleão.",
	"Aquele nervinho debaixo da língua.",
	"Um cu tão apertado que não passa nem Wi-Fi.",
	"Uma buceta larga como o Túnel Rebouças.",
	"Prepúcio crocante.",
	"Testículos assimétricos.",
	"Um pênis torto para a esquerda.",
	"Seios caídos batendo no umbigo.",
	"Um cu branquinho e depilado.",
	"A glande sensível demais.",
	"Vômito de feijoada.",
	"Limpar a bunda com a mão.",
	"Uma poça de diarreia.",
	"O cheiro de sêmen com água sanitária.",
	"Comer milho direto da bosta.",
	"Esmegma acumulado de três semanas.",
	"Passar esmegma na torrada.",
	"Beber menstruação direto da fonte.",
	"Um tampão usado como saquinho de chá.",
	"Um banho de porra morna.",
	"Gargarejar com porra.",
	"Oito litros de sêmen de cavalo.",
	"Uma cagada que bate na água e molha a bunda.",
	"Diarreia explosiva no primeiro encontro.",
	"Um toletão de bosta boiando na piscina.",
	"Beijar de língua logo após vomitar.",
	"Pedaços de cenoura no vômito.",
	"Peidar no elevador lotado e culpar o gordo.",
	"Aquele peido 'molhado' que exige verificação.",
	"O cheiro do banheiro da rodoviária.",
	"Palitar os dentes com a unha do pé.",
	"Cheirar a roupa íntima pra ver se dá pra usar.",
	"Corrimento vaginal com cor de iogurte.",
	"Suor de gordo na dobra do pescoço.",
	"Uma ferida com pus.",
	"Catota de nariz colada debaixo da mesa.",
	"A crosta de leite na cabeça do bebê.",
	"Baba de velho.",
	"Urina escura de quem não bebe água há dias.",
	"Um \"Golden Shower\" surpresa.",
	"O suco do lixo.",
	"Cera de ouvido amarga.",
	"Um arroto com gosto de ovo podre.",
	"A água da salsicha.",
	"Um pedaço de alface no dente.",
	"O líquido que sai do presunto.",
	"Cuspe grosso.",
	"Bosta de vaca fresca.",
	"Fralda geriátrica cheia.",
	"O cheiro de queijo do pinto sujo.",
	"Um boquete mal feito.",
	"Ouvir o gemidão do Zap no máximo.",
	"Cagar no pau durante o anal.",
	"Ser pego pela mãe no meio de uma punheta furiosa.",
	"Masturbação compulsiva em velórios.",
	"Usar lixa d'água como lubrificante.",
	"Um boquete com muitos dentes.",
	"Lamber o cu suado do motorista de ônibus.",
	"A fantasia sexual secreta da sua mãe.",
	"Transar com a prima no churrasco de domingo.",
	"Roubar sepultura para fins românticos.",
	"Transar com cinzas de cremação.",
	"Pornô japonês com tentáculos.",
	"As peles flácidas da vovó.",
	"Dentaduras caindo durante o oral.",
	"Dois anões cagando num balde.",
	"Fisting sem lubrificante.",
	"A palavra de segurança é 'Bolsonaro'.",
	"Bater uma com mamão.",
	"Uma viagem para Pelotas (e eu sei o que você fez lá).",
	"Sexo com animais de grande porte.",
	"Chupar o dedão do pé sujo.",
	"Fingir orgasmo para acabar logo.",
	"Usar Vick Vaporub na glande.",
	"Sexo no banheiro químico.",
	"Uma suruba na casa de repouso.",
	"Comer o cu de quem tá lendo.",
	"Gozar nas costas de um desconhecido no metrô.",
	"Levar uma dedada no meio da briga.",
	"O clássico \"papai e mamãe\" sem graça.",
	"Filmar pornô amador com câmera Tekpix.",
	"Usar calcinha da irmã.",
	"Cheirar banco de bicicleta.",
	"Masturbação cruzada com o melhor amigo.",
	"Perder a virgindade com uma prostituta triste.",
	"Sexo tântrico que nunca termina.",
	"Um beijo grego após uma feijoada.",
	"Lamber o corrimão do metrô.",
	"Introduzir objetos não identificados no reto.",
	"A posição \"frango assado\".",
	"A grávida de Taubaté.",
	"O fantasma do Clodovil.",
	"Vampeta pelado na G Magazine.",
	"O Lula sem um dedo.",
	"A facada do Bolsonaro.",
	"Suzane von Richthofen no dia das mães.",
	"O goleiro Bruno servindo ração para cães.",
	"Inês Brasil gritando \"Alô, alô, graças a Deus\".",
	"O silicone industrial da Inês Brasil.",
	"A barriga de almofada da Grávida de Taubaté.",
	"Ser atropelado pelo Fofão da Carreta Furacão.",
	"Canarinho Pistola.",
	"O Negão do WhatsApp.",
	"O Bebê Diabo do Notícias Populares.",
	"A Loira do Banheiro dando descarga.",
	"O ET de Varginha.",
	"O Louro José (póstumo).",
	"Ana Maria Braga de ressaca.",
	"O Lombardi (voz do além).",
	"Gretchen e seus 17 casamentos.",
	"Andressa Urach na fase evangélica.",
	"Andressa Urach na fase Miss Bumbum.",
	"O Padre do Balão voando para o nada.",
	"Menino do Acre.",
	"Dercy Gonçalves mostrando os peitos.",
	"Gilberto Barros (o Leão) sendo racista.",
	"Datena gritando \"Me dá imagens!\".",
	"O japonês da Federal.",
	"Dilma saudando a mandioca.",
	"Um sósia do Vin Diesel brasileiro.",
	"A risada do Carlos Alberto de Nóbrega.",
	"Xuxa falando ao contrário.",
	"Palmirinha esquecendo a receita.",
	"O boneco Chucky.",
	"O Chupacabra atacando o galinheiro.",
	"O ET Bilu buscando conhecimento.",
	"Véio da Havan vestido de super-herói.",
	"Pablo Vittar indo longe demais.",
	"Neymar caindo.",
	"Ronaldinho Gaúcho nos rolês aleatórios.",
	"As moléculas de água que viram Duréculas.",
	"O Tratado de Tortas Ilhas.",
	"O índice de fecundidade de dois machos.",
	"Lenini e Stalone como figuras do comunismo.",
	"O oxigênio inventado por Lavoisier antes de ser guilhotinado.",
	"Baixar tinta para impressora pelo Google.",
	"Ralar o leite para fazer leite em pó.",
	"Fazer amor com um O.B.",
	"Grupo da Família com Bom Dia e Fake News.",
	"O gemidão do Zap na missa de sétimo dia.",
	"Comentários do G1.",
	"Um textão no Facebook.",
	"Cancelamento no Twitter.",
	"Um vídeo do TikTok com dancinha vergonhosa.",
	"O filtro de cachorro do Instagram.",
	"Coach quântico reprogramando seu DNA.",
	"Vender pack de pé no OnlyFans.",
	"NFT de macaco.",
	"O urubu do PIX.",
	"Golpe do boleto falso.",
	"A Grávida de Taubaté.",
	"O meme do caixão.",
	"Bora Bill.",
	"Luva de Pedreiro.",
	"Aquele áudio da mulher gritando \"Attenzione Pickpocket\".",
	"O patriota do caminhão.",
	"O fantasma do comunismo.",
	"Kit Gay.",
	"Mamadeira de piroca.",
	"Terraplanistas.",
	"O \"shape\" inexplicável do Padre Marcelo Rossi.",
	"A sandália da humildade.",
	"Banheira do Gugu.",
	"Teste de fidelidade do João Kleber.",
	"O \"Para nossa alegria\".",
	"E morre a inesquecível...",
	"Senhora? Senhora?",
	"Mamilos são polêmicos.",
	"Hoje não, hoje não... hoje sim!",
	"Cê quer ver meu pau?",
	"Crianças com armas.",
	"Aborto caseiro com cabide.",
	"Cheirar cola de sapateiro.",
	"Mendigos brigando por um pedaço de pão.",
	"Bala perdida no café da manhã.",
	"Arrastão na praia de Copacabana.",
	"A tornozeleira eletrônica do Lula.",
	"Rachadinha no gabinete.",
	"Vacina de vento.",
	"Cota para brancos.",
	"Racismo reverso.",
	"Um anão vestido de palhaço assassino.",
	"Milicianos cobrando taxa de segurança.",
	"Tráfico de órgãos no mercado negro.",
	"A cracolândia às 3 da manhã.",
	"Um corpo boiando na Baía de Guanabara.",
	"A elite branca brasileira.",
	"Trabalho escravo em vinícolas.",
	"Queimar a Amazônia para plantar soja.",
	"Garimpo ilegal em terras indígenas.",
	"A PM subindo o morro.",
	"Um político com dólares na cueca.",
	"A bancada da bala, do boi e da bíblia.",
	"O sistema carcerário brasileiro.",
	"Chacina na Candelária.",
	"O incêndio do Museu Nacional.",
	"A barragem de Brumadinho estourando.",
	"Favelas pegando fogo.",
	"Merenda escolar feita de bolacha e água.",
	"Ônibus queimado em protesto.",
	"Assalto à mão armada.",
	"Sequestro relâmpago.",
	"O Comando Vermelho.",
	"O PCC.",
	"Jogo do Bicho.",
	"Máquina caça-níquel no bar da esquina.",
	"Cigarro paraguaio.",
	"Uísque falsificado com metanol.",
	"A \"Saidinha\" de Natal dos presos.",
	"Um juiz que se acha Deus.",
	"Saco de lixo de peruca.",
	"Paquita do Capeta.",
	"Resto de parto.",
	"Filhote de cruz credo.",
	"Peido de jumenta.",
	"Cabeça de melão.",
	"Homem é igual caminhão basculante.",
	"No baralho da vida, sou apenas um curinga.",
	"Se chiar resolvesse, Sonrisal não morria afogado.",
	"Mulher de amigo meu pra mim é homem.",
	"Casamento é igual avenida: começa no asfalto e termina no barro.",
	"Corno manso.",
	"Filho da puta.",
	"Arrombado.",
	"Zé Ruela.",
	"Pela-saco.",
	"Chupa-cabra.",
	"Bosta n'água.",
	"Resto de aborto.",
	"Atrasado é quem está na minha frente.",
	"Deus criou o mundo, mas quem paga a conta sou eu.",
	"Dirijo com cuidado para não acordar sua mãe no porta-malas.",
	"Não sou dono do mundo, mas sou filho do dono.",
	"Nasci pelado, careca e sem dente. O que vier é lucro.",
	"80km/h ou a família chora.",
	"Se ferradura desse sorte, burro não puxava carroça.",
	"Esteira de gordo é buffet.",
	"Mulher e café: frio não serve pra nada.",
	"Vaso ruim não quebra.",
	"Há males que vêm para o bem... e há bens que vêm para os meus males.",
	"Um vibrador de 30cm.",
	"Uma arma carregada.",
	"Um feto.",
	"O vazio existencial.",
	"A democracia brasileira.",
	"O patriarcado.",
	"Cagando sangue.",
	"Dando o cu e rindo.",
	"Espancando um morador de rua.",
	"Achei que era peido mas era bosta.",
	"Um unicórnio com ereção.",
	"Papai Noel pedófilo.",
	"Jesus Cristo andando de skate.",
	"A própria morte pedindo carona.",
	"Um ataque de pânico no meio do shopping.",
	"Suicídio social.",
	"Um tumor benigno com rosto humano.",
	"A sensação de ter uma barata no ouvido.",
	"Comer vidro moído.",
	"Beber gasolina.",
	"Um palhaço triste fumando crack.",
	"Uma boneca inflável furada.",
	"O silêncio constrangedor no elevador.",
	"A depressão pós-parto.",
	"Um câncer de próstata.",
	"A terceira guerra mundial.",
	"Um meteoro caindo em Brasília.",
	"A extinção da raça humana.",
	"O apocalipse zumbi iniciado no Carnaval.",
	"Simplesmente desistir de viver.",
	"Uma rola negra gigante.",
	"Um cu clareado.",
	"Um tumor cerebral.",
	"Um balde de cabecas de peixe.",
	"Uma surra de criar bicho.",
	"Um isopor cheio de orgaos.",
	"Um cadaver.",
	"Um raio da morte.",
	"Uma camisinha furada.",
	"Uma festa de aniversario decepcionante.",
	"Um falcao usando um bone.",
	"Um feto.",
	"Uma boca suja.",
	"Um antilope com gases.",
	"Uma caricia suave na parte interna da coxa.",
	"Uma boa cheirada.",
	"Uma maldicao cigana.",
	"Uma montagem de volei homoerotico.",
	"Uma situacao caotica.",
	"Uma vida inteira de tristeza.",
	"Uma espiadinha.",
	"Um homem a beira do orgasmo.",
	"Uma danca do acasalamento.",
	"Um micropenis.",
	"Um homem de meia-idade de patins.",
	"Um mimico tendo um derrame.",
	"Um macaco fumando charuto.",
	"Um leao de zoologico deprimido.",
	"Um assassinato cruel.",
	"Uma piramide de cabecas decepadas.",
	"Um chapeu muito legal.",
	"Um mongoloide robusto.",
	"Uma punheta triste.",
	"Uma surpresa salgadinha.",
	"Um solo de saxofone.",
	"Um mar de problemas.",
	"Uma tartaruga mordendo a ponta do seu pinto.",
	"Um pentelho solto.",
	"Uma arminha de agua cheia de xixi de gato.",
	"Uma detonacao termonuclear.",
	"Um paradoxo de viagem no tempo.",
	"Um cavalo minusculo.",
	"Um moinho de vento cheio de cadaveres.",
	"A perspectiva de uma mulher.",
	"Abstinencia.",
	"A vencedora do Oscar, Meryl Streep.",
	"Aceitar as coisas como elas sao.",
	"Escuta ativa.",
	"Ritalina.",
	"Fraldas geriatricas.",
	"Criancas africanas.",
	"Agricultura.",
	"AIDS.",
	"Alcoolismo.",
	"Camarao a vontade por R$ 14,90.",
	"Coroinhas.",
	"Gladiadores Americanos.",
	"Amputados.",
	"Contas anais (Anal beads).",
	"Fissuras anais.",
	"Angelina Jolie.",
	"Mais um filme de vampiro maldito.",
	"Arnold Schwarzenegger.",
	"Asiaticos que nao sao bons em matematica.",
	"Calcas de couro sem bunda.",
	"Atitude.",
	"Auschwitz.",
	"Culinaria mexicana autentica.",
	"Autocanibalismo.",
	"Desodorante AXE.",
	"Bolas.",
	"Barack Obama.",
	"Decencia humana basica.",
	"Batman.",
	"Lutar contra um pinguim de 30 metros.",
	"Ataques de urso.",
	"Cortinas de carne (labios vaginais).",
	"Ser escroto com criancas.",
	"Ser a porra de um feiticeiro.",
	"Ser fabulosa.",
	"Ser marginalizado.",
	"Estar em chamas.",
	"Ser rico.",
	"O mundo de Beakman.",
	"Comer ate vomitar (bulimia).",
	"Vadias.",
	"Pessoas negras.",
	"Ostentacao.",
	"Peidos com sangue.",
	"Boquetes.",
	"Meleca de nariz.",
	"Boris, o Martelo do Amor Sovietico.",
	"Criadores de galinha bosnios.",
	"Comecar a cantar e dancar do nada.",
	"Britney Spears aos 55 anos.",
	"Pessoas pardas.",
	"Passivos com bunda grande.",
	"Conversa fiada.",
	"Cartas Contra a Humanidade.",
	"Catapultas.",
	"Centauros.",
	"Motosserras no lugar das maos.",
	"Carisma.",
	"Trapacear nas Paraolimpiadas.",
	"Abuso infantil.",
	"Concursos de beleza infantil.",
	"Criancas na coleira.",
	"Cavalheirismo.",
	"Christopher Walken.",
	"Baixas civis.",
	"Mariscos.",
	"Tons classistas.",
	"Limpar suas entranhas com uma escova de mamadeira.",
	"Abortos com cabide.",
	"Rinha de galo.",
	"Faculdade.",
	"Esconder um pau duro.",
	"Consultores.",
	"Dar uma apalpada.",
	"Tossir dentro de uma vagina.",
	"Conde Dracula.",
	"Divida paralisante.",
	"Metanfetamina.",
	"Fazer conchinha.",
	"Representantes de atendimento ao cliente.",
	"Melhorias ciberneticas.",
	"Problemas paternos (Daddy issues).",
	"O cinto do papai.",
	"Dancar com uma vassoura.",
	"Forcas sombrias e misteriosas.",
	"Darth Vader.",
	"Boa noite Cinderela.",
	"Bebes mortos.",
	"Pais mortos.",
	"Morte por cachorro Chow Chow.",
	"Tirar a virgindade da princesa.",
	"Protetores dentais (para sexo oral).",
	"Destruir as evidencias.",
	"Dedos de pinto.",
	"Jantar com recortes de papelao do elenco de \"Friends\".",
	"Fraldas sujas.",
	"Febre da discoteca.",
	"Fazer no bumbum.",
	"Fazer a coisa certa.",
	"Pizza de sobremesa de Oreo da Domino's.",
	"Donald Trump.",
	"Dupla penetracao.",
	"Beber sozinho.",
	"Derrubar um lustre em seus inimigos e subir pela corda.",
	"Ansia de vomito.",
	"Arremesso de anao.",
	"Morrer.",
	"Comer todos os biscoitos antes do evento beneficente da AIDS.",
	"Comer um albino.",
	"Comer o ultimo bisao conhecido.",
	"Calcinha comestivel.",
	"Homens japoneses idosos.",
	"Cerca eletrica.",
	"Celulas-tronco embrionarias.",
	"Palmirinha.",
	"Emma Watson.",
	"Emocoes.",
	"Mulheres escandinavas enormes.",
	"Disfuncao eretil.",
	"Estrogenio.",
	"Limpeza etnica.",
	"Eugenia.",
	"Perfume Euphoria da Calvin Klein.",
	"Exatamente o que voce esperaria.",
	"Trocar gentilezas.",
	"Existir.",
	"Esperar um arroto e vomitar.",
	"Explosoes.",
	"Fabricar estatisticas.",
	"Fome.",
	"Racao de gato cara.",
	"Peidar e sair andando.",
	"Medo de si mesmo.",
	"Alimentar a Jojo Todynho.",
	"Sindrome alcoolica fetal.",
	"Caganeira ardida.",
	"Pudim de passas.",
	"Encontrar um esqueleto.",
	"Encontrar o Wally.",
	"Pintura a dedo.",
	"Dedada.",
	"Disparar um rifle para o ar enquanto esta atochado numa porca gritando.",
	"Sanduiche de 30cm do Subway.",
	"Enchentes repentinas.",
	"Bacterias comedoras de carne.",
	"Aves que nao voam.",
	"Cobras sexuais voadoras.",
	"Prepucio.",
	"Esquecer o 11 de setembro.",
	"O ex-presidente George W. Bush.",
	"Amostras gratis.",
	"Atrito.",
	"Fogo amigo.",
	"Amigos que comem todos os lanches.",
	"Amizade colorida.",
	"Saltitar.",
	"Nudez frontal total.",
	"Rimas descoladas.",
	"Gandalf.",
	"Gary Coleman.",
	"Gayzificado.",
	"Gansos.",
	"Supersoldados geneticamente modificados.",
	"Genghis Khan.",
	"Piercing genital.",
	"O almiscar de George Clooney.",
	"Porno de masmorra alemao.",
	"Ser abduzido por alienigenas.",
	"Ficar bebado com enxaguante bucal.",
	"Entrar nas calcas dela.",
	"Ficar pelado e assistir Nickelodeon.",
	"Ficar muito chapado.",
	"Ficar tao bravo a ponto de ter uma erecao.",
	"Fantasmas.",
	"Garotas.",
	"Dar 110% de si.",
	"Gladys Knight e os Pips.",
	"Glenn Beck (apresentador conservador) estar certo sobre tudo.",
	"Glenn Beck pegando gripe aviaria.",
	"Aquecimento global.",
	"Gloryholes.",
	"Cabras comendo latas.",
	"Goblins.",
	"Deus.",
	"Danoninho.",
	"Chuva dourada (Golden shower).",
	"Boa gramatica.",
	"Vovo.",
	"Cinzas do vovo.",
	"Violencia grafica, linguagem adulta e algum conteudo sexual.",
	"Roubo de tumulos.",
	"Caras que nao ligam de volta.",
	"Preliminares meia-boca.",
	"Fanfic erotica de Harry Potter.",
	"Orfaos comoventes.",
	"Sua Alteza Real, a Rainha Elizabeth II.",
	"Heteronormatividade.",
	"O olhar mortal de Hillary Clinton.",
	"Hipsters.",
	"Revisionismo historico.",
	"Video caseiro da Oprah chorando em cima de um prato de comida congelada.",
	"Moradores de rua.",
	"Esperanca.",
	"Injecoes de hormonio.",
	"Acidentes horriveis de depilacao a laser.",
	"Carne de cavalo.",
	"Queijo quente derretido.",
	"Pessoas atraentes.",
	"Salgados congelados.",
	"Hulk Hogan.",
	"Furacao Katrina.",
	"Impotencia.",
	"Dispositivos explosivos improvisados.",
	"Incesto.",
	"Iodelar de forma inapropriada.",
	"Acidentes industriais.",
	"Inserir um pote de vidro no meu anus.",
	"Invadir a Polonia.",
	"Italianos.",
	"Buceta cocando.",
	"Pesquisas de satisfacao do consumidor.",
	"Os restos cancerigenos de uma subcelebridade.",
	"Shibari (tecnica japonesa de cordas).",
	"Jean-Claude Van Damme.",
	"Jeff Goldblum.",
	"Bater uma numa piscina de lagrimas de criancas.",
	"Black power de judeu.",
	"Fraternidades judaicas.",
	"Bla-bla-bla.",
	"Joe Biden.",
	"John Wilkes Booth.",
	"Judge Judy (juiza de TV).",
	"Justin Bieber.",
	"Pilotos kamikazes.",
	"Kanye West.",
	"Keanu Reeves.",
	"Beber de cabeca para baixo no barril de chopp.",
	"Criancas com cancer no cu.",
	"Kim Jong-il.",
	"Krampus.",
	"O microfone de Kurt Cobain.",
	"Lactacao.",
	"Lady Gaga.",
	"O testiculo perdido de Lance Armstrong.",
	"Minas terrestres.",
	"Botar um ovo.",
	"Deixar um recado de voz estranho.",
	"Lepra.",
	"Subir de nivel.",
	"Lamber coisas para reivindica-las como suas.",
	"Lipoaspiracao.",
	"Tetano.",
	"Lingua solta.",
	"Fantasias de lenhador.",
	"Lancheira escolar.",
	"Vadia mentirosa.",
	"Doenca da vaca louca.",
	"Madeleine McCann.",
	"Magneto.",
	"Fazer biquinho.",
	"Fazer os penis se beijarem.",
	"Fazer o gesto da mascara cirurgica.",
	"Carne de macho.",
	"Masturbacao.",
	"Tempo para mim.",
	"MechaHitler.",
	"Cobertura da midia.",
	"Jantar Medieval com Torneio.",
	"Homens.",
	"Menstruacao.",
	"Michael Jackson.",
	"Os bracos da Michelle Obama.",
	"Autismo leve.",
	"Mugir.",
	"Ambiguidade moral.",
	"A voz do Morgan Freeman.",
	"Herpes labial.",
	"Mr. Clean, logo atras de voce.",
	"Maome (Que a Paz Esteja Com Ele).",
	"Multiplas facadas.",
	"Destruicao mutua assegurada.",
	"Minha colecao de brinquedos sexuais de alta tecnologia.",
	"Minha primeira morte.",
	"Meus genitais.",
	"Minha comissao de frente.",
	"Meus demonios interiores.",
	"Meu facao.",
	"Meu status de relacionamento.",
	"Minha vida sexual.",
	"Minha alma.",
	"Minha vagina.",
	"Natalie Portman.",
	"Aumento natural masculino.",
	"Selecao natural.",
	"Nazistas.",
	"Necrofilia.",
	"Neil Patrick Harris.",
	"Musica New Age.",
	"Nickelback.",
	"Nicolas Cage.",
	"Laminas no mamilo.",
	"Polucao noturna.",
	"Nao dar a minima para o Terceiro Mundo.",
	"Nao retribuir sexo oral.",
	"Meninos escravos nubeis.",
	"Golpes de nunchaku.",
	"Obesidade.",
	"Permanencia de objeto.",
	"Cheiro de velho.",
	"Musica de fundo sinistra.",
	"Uma teta para fora.",
	"Um trilhao de dolares.",
	"Oompa-Loompas.",
	"Polegares opositores.",
	"Supercompensacao.",
	"Dominar seu pai.",
	"Pirulitos gigantes.",
	"Sexo de pandas.",
	"Abrir o Mar Vermelho.",
	"Estraga-prazeres.",
	"Travestis passaveis.",
	"Expelir uma pedra nos rins.",
	"Post-its passivo-agressivos.",
	"Pedofilos.",
	"Fazer um pouquinho de xixi.",
	"Inveja do penis.",
	"Pegar garotas na clinica de aborto.",
	"Fotos de peitos.",
	"Guerra de travesseiro.",
	"Bukkake pixelado.",
	"Brutalidade policial.",
	"Cagar um no cu do outro. Para sempre.",
	"Pessimas escolhas de vida."
]

# ============================================
# CARTAS INTERNACIONAIS (INGLES)
# ============================================
# Estas cartas aparecem APENAS quando o idioma e Ingles.
const BLACK_CARDS_EN = [
	"Why can't I sleep at night?",
	"I got 99 problems but ____ ain't one.",
	"What's the next Happy Meal toy?",
	"Daddy, why is mommy crying?",
	"in the new Disney movie, Hannah Montana struggles with: ____.",
	"Instead of coal, Santa now gives the bad children: ____.",
	"What is Batman's guilty pleasure?",
	"Man, this is gonna be the best ____ ever!",
	"TSA guidelines now prohibit ____ on airplanes.",
	"What ended my last relationship?",
	"War! What is it good for?",
	"What does Dick Cheney prefer to waterboarding?",
	"____. That's how I want to die.",
	"What's that smell?",
	"I drink to forget: ____.",
	"New from Mattel: Barbie's ____ accessory.",
	"What helps Obama unwind?",
	"During sex, I like to think about: ____.",
	"What did I bring back from Mexico?",
	"When I am Prime Minister, I will create the Ministry of: ____.",
	"What's the crusty stuff on my couch?",
	"Next on MTV: Pimp My ____.",
	"Step 1: ____. Step 2: ____. Step 3: Profit.",
	"They said we were crazy. They said we couldn't put ____ inside of ____. They were wrong.",
	"Sorry everyone, I just ____.",
	"Life for American Indians was forever changed when the White Man introduced them to: ____.",
	"What's the most emo?",
	"Coming to Broadway this season, ____: The Musical.",
	"The class field trip was completely ruined by: ____.",
	"In a world ravaged by ____, our only solace is ____.",
	"I never truly understood ____ until I encountered ____.",
	"Rumor has it that Vladimir Putin's favorite dish is: ____.",
	"What are my parents hiding from me?",
	"____. Good to the last drop.",
	"What did the US military airdrop to the children of Afghanistan?",
	"What am I giving up for Lent?",
	"In M. Night Shyamalan's new movie, Bruce Willis discovers that he had really been ____ all along.",
	"How did I lose my virginity?",
	"The blind date was going horribly until we discovered our shared love for: ____.",
	"____. It's a trap!",
	"A romantic, candlelit dinner would be incomplete without: ____.",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on: ____.",
	"____. Betcha can't have just one!",
	"It's a pity that kids these days are all getting involved with: ____.",
	"What totally destroyed my asshole?",
	"My country, 'tis of thee, sweet land of: ____.",
	"What gives me uncontrollable gas?",
	"The new Bible features a hip, modern Jesus who forgives: ____.",
	"What is the secret to a happy marriage?",
	"My gym teacher got fired for adding ____ to the obstacle course.",
	"The Pope has officially canonized the patron saint of: ____.",
	"____. High five, bro.",
	"I'm sorry, Professor, but I couldn't complete my homework because of: ____.",
	"What's there a ton of in heaven?",
	"White people like ____.",
	"Why am I sticky?",
	"Today on Maury: \"Help! My son is ____!\"",
	"____. Kid tested, mother approved.",
	"Before I kill you, Mr. Bond, I must show you: ____.",
	"What's the new fad diet?",
	"Major League Baseball has banned ____ for giving players an unfair advantage.",
	"If God didn't want us to enjoy ____, he wouldn't have given us ____.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with: ____.",
	"What's the gift that keeps on giving?",
	"In the beginning, there was ____. And the Lord said, \"Let there be ____.\"",
	"New from Pfizer: Viagra for: ____.",
	"The healing process began when I joined a support group for victims of: ____.",
	"The Exorcist of Emily Rose was actually caused by: ____.",
	"What is the worst thing you can find in a Chinese food buffet?",
	"____. The breakfast of champions.",
	"When I'm in prison, I'll hide ____ inside my anal cavity.",
	"The internet is for: ____.",
	"Behold, the Four Horsemen of the Apocalypse! War, Famine, Pestilence, and: ____.",
	"To produce the perfect erection, you must use: ____.",
	"What makes me projectile vomit?",
	"Science will never explain the origin of: ____.",
	"During his midlife crisis, my dad got into: ____.",
	"Wake up, America. The terrorists have won. They have: ____.",
	"In his final moments, Michael Jackson mumbled about: ____.",
	"____. It's what's for dinner.",
	"Only two things in life are certain: death and: ____.",
	"Who is the most dangerous man in the world?",
	"The CIA is currently monitoring: ____.",
	"What's the most annoying thing about my coworkers?",
	"The best pickup line starts with: ____.",
	"My therapist says I have an unhealthy obsession with: ____.",
	"The prophecy foretold that the world would end with: ____.",
	"What's hiding under my bed?",
	"I finally found a use for: ____.",
	"____. Because I'm worth it.",
	"The only thing that gets me hard anymore is: ____.",
	"What is the ultimate forbidden fruit?",
	"My autobiography is titled \"____: A Love Story.\"",
	"The Nobel Peace Prize goes to: ____.",
	"What happens in Vegas stays in Vegas, except for: ____.",
	"Why did the chicken cross the road?",
	"____. Not even once.",
	"Who let the dogs out?",
	"Click here for hot singles in your area looking for: ____.",
	"The secret ingredient in Grandma's cookies is: ____."
]

const WHITE_CARDS_EN = [
	"A big black dick.",
	"A bleached asshole.",
	"A brain tumor.",
	"A bucket of fish heads.",
	"A can of whoop-ass.",
	"A cooler full of organs.",
	"A corpse.",
	"A death ray.",
	"A defective condom.",
	"A disappointing birthday party.",
	"A falcon with a cap on its head.",
	"A fetus.",
	"A foul mouth.",
	"A gassy antelope.",
	"A gentle caress of the inner thigh.",
	"A good sniff.",
	"A Gypsy curse.",
	"A homoerotic volleyball montage.",
	"A hot mess.",
	"A lifetime of sadness.",
	"A look-see.",
	"A man on the brink of orgasm.",
	"A mating display.",
	"A micropenis.",
	"A middle-aged man on roller skates.",
	"A mime having a stroke.",
	"A monkey smoking a cigar.",
	"A mopey zoo lion.",
	"A murder most foul.",
	"A pyramid of severed heads.",
	"A really cool hat.",
	"A robust mongoloid.",
	"A sad handjob.",
	"A salty surprise.",
	"A saxophone solo.",
	"A sea of troubles.",
	"A snapping turtle biting the tip of your penis.",
	"A stray pube.",
	"A Super Soaker™ full of cat pee.",
	"A thermonuclear detonation.",
	"A time travel paradox.",
	"A tiny horse.",
	"A windmill full of corpses.",
	"A woman's perspective.",
	"Abstinence.",
	"Academy Award winner Meryl Streep.",
	"Accepting the way things are.",
	"Active listening.",
	"Adderall™.",
	"Adult Diapers.",
	"African children.",
	"Agriculture.",
	"AIDS.",
	"Alcoholism.",
	"All-you-can-eat shrimp for $4.99.",
	"Altar boys.",
	"American Gladiators.",
	"Amputees.",
	"Anal beads.",
	"Anal fissures.",
	"Angelina Jolie.",
	"Another goddamn vampire movie.",
	"Arnold Schwarzenegger.",
	"Asians who aren't good at math.",
	"Assless chaps.",
	"Attitude.",
	"Auschwitz.",
	"Authentic Mexican cuisine.",
	"Autocannibalism.",
	"AXE Body Spray.",
	"Balls.",
	"Barack Obama.",
	"Basic human decency.",
	"Batman.",
	"Battling a 100-foot penguin.",
	"Bear attacks.",
	"Beef curtains.",
	"Being a dick to children.",
	"Being a motherfucking sorcerer.",
	"Being fabulous.",
	"Being marginalized.",
	"Being on fire.",
	"Being rich.",
	"Bill Nye the Science Guy.",
	"Bingeing and purging.",
	"Bitches.",
	"Black people.",
	"Bling.",
	"Blood farts.",
	"Blowjobs.",
	"Boogers.",
	"Boris the Soviet Love Hammer.",
	"Bosnian chicken farmers.",
	"Breaking out into song and dance.",
	"Britney Spears at 55.",
	"Brown people.",
	"Bubble butt bottom boys.",
	"Bullshit.",
	"Cards Against Humanity.",
	"Catapults.",
	"Centaurs.",
	"Chainsaws for hands.",
	"Charisma.",
	"Cheating in the Special Olympics.",
	"Child abuse.",
	"Child beauty pageants.",
	"Children on leashes.",
	"Chivalry.",
	"Christopher Walken.",
	"Civilian casualties.",
	"Clams.",
	"Classist undertones.",
	"Cleaning out your insides with a bottle brush.",
	"Coat hanger abortions.",
	"Cockfights.",
	"College.",
	"Concealing a boner.",
	"Consultants.",
	"Copping a feel.",
	"Coughing into a vagina.",
	"Count Chocula.",
	"Crippling debt.",
	"Crystal meth.",
	"Cuddling.",
	"Customer service representatives.",
	"Cybernetic enhancements.",
	"Daddy issues.",
	"Daddy's belt.",
	"Dancing with a broom.",
	"Dark and mysterious forces.",
	"Darth Vader.",
	"Date rape.",
	"Dead babies.",
	"Dead parents.",
	"Death by Chow Chow.",
	"Deflowering the princess.",
	"Dental dams.",
	"Destroying the evidence.",
	"Dick fingers.",
	"Dining with cardboard cutouts of the cast of \"Friends.\"",
	"Dirty diapers.",
	"Disco fever.",
	"Doin' it in the butt.",
	"Doing the right thing.",
	"Domino's™ Oreo™ Dessert Pizza.",
	"Donald Trump.",
	"Double penetration.",
	"Drinking alone.",
	"Dropping a chandelier on your enemies and riding the rope up.",
	"Dry heaving.",
	"Dwarf tossing.",
	"Dying.",
	"Eating all of the cookies before the AIDS bake-sale.",
	"Eating an albino.",
	"Eating the last known bison.",
	"Edible underpants.",
	"Elderly Japanese men.",
	"Electric fence.",
	"Embryonic stem cells.",
	"Emeril Lagasse.",
	"Emma Watson.",
	"Emotions.",
	"Enormous Scandinavian women.",
	"Erectile dysfunction.",
	"Estrogen.",
	"Ethnic cleansing.",
	"Eugenics.",
	"Euphoria™ by Calvin Klein.",
	"Exactly what you'd expect.",
	"Exchanging pleasantries.",
	"Existing.",
	"Expecting a burp and vomiting.",
	"Explosions.",
	"Fabricating statistics.",
	"Famine.",
	"Fancy Feast.",
	"Farting and walking away.",
	"Fear of self.",
	"Feeding Rosie O'Donnell.",
	"Fetal alcohol syndrome.",
	"Fiery poops.",
	"Figgy pudding.",
	"Finding a skeleton.",
	"Finding Waldo.",
	"Finger painting.",
	"Fingering.",
	"Firing a rifle into the air while balls deep in a squealing hog.",
	"Five-Dollar Footlongs™.",
	"Flash floods.",
	"Flesh-eating bacteria.",
	"Flightless birds.",
	"Flying sex snakes.",
	"Foreskin.",
	"Forgetting the Alamo.",
	"Former President George W. Bush.",
	"Free samples.",
	"Friction.",
	"Friendly fire.",
	"Friends who eat all the snacks.",
	"Friends with benefits.",
	"Frolicking.",
	"Full frontal nudity.",
	"Funky fresh rhymes.",
	"Gandalf.",
	"Gary Coleman.",
	"Gayed.",
	"Geese.",
	"Genetically engineered super-soldiers.",
	"Genghis Khan.",
	"Genital piercings.",
	"George Clooney's musk.",
	"German dungeon porn.",
	"Getting abducted by aliens.",
	"Getting drunk on mouthwash.",
	"Getting in her pants.",
	"Getting naked and watching Nickelodeon.",
	"Getting really high.",
	"Getting so angry that you pop a boner.",
	"Ghosts.",
	"Girls.",
	"Giving 110%.",
	"Gladys Knight and the Pips.",
	"Glenn Beck being right about everything.",
	"Glenn Beck catching bird flu.",
	"Global warming.",
	"Gloryholes.",
	"Goats eating cans.",
	"Goblins.",
	"God.",
	"GoGurt.",
	"Golden showers.",
	"Good grammar.",
	"Grandma.",
	"Grandpa's ashes.",
	"Graphic violence, adult language, and some sexual content.",
	"Grave robbing.",
	"Guys who don't call.",
	"Half-assed foreplay.",
	"Harry Potter erotica.",
	"Heartwarming orphans.",
	"Her Royal Highness, Queen Elizabeth II.",
	"Heteronormativity.",
	"Hillary Clinton's death stare.",
	"Hipsters.",
	"Historical revisionism.",
	"Home video of Oprah sobbing into a Lean Cuisine®.",
	"Homeless people.",
	"Hope.",
	"Hormone injections.",
	"Horrifying laser hair removal accidents.",
	"Horse meat.",
	"Hot cheese.",
	"Hot people.",
	"Hot Pockets®.",
	"Hulk Hogan.",
	"Hurricane Katrina.",
	"Impotence.",
	"Improvised explosive devices.",
	"Incest.",
	"Inappropriate yodeling.",
	"Industrial accidents.",
	"Inserting a Mason jar into my anus.",
	"Invading Poland.",
	"Italians.",
	"Itchy pussy.",
	"J.D. Power and his associates.",
	"Jade Goody's cancerous remains.",
	"Japanese rope technique.",
	"Jean-Claude Van Damme.",
	"Jeff Goldblum.",
	"Jerking off into a pool of children's tears.",
	"Jew-fros."
]
