extends Node
class_name AbsurdCardsData

# ============================================
# FUNCOES AUXILIARES
# ============================================

static func get_packs_info() -> Array:
	return [
		{
			"id": "classico",
			"name": "CLÁSSICO",
			"description": "O jogo original. Perguntas e respostas absurdas para destruir amizades.",
			"available": true,
			"black_count": BLACK_CARDS_BR.size(),
			"white_count": WHITE_CARDS_BR.size()
		},
		{
			"id": "insano",
			"name": "INSANO",
			"description": "Para quem acha que o clássico é leve demais. Conteúdo +18 extremo.",
			"available": false, # Em breve
			"black_count": 0,
			"white_count": 0
		},
		{
			"id": "meme",
			"name": "MEMES BR",
			"description": "Um pack focado na cultura da internet brasileira.",
			"available": false, # Em breve
			"black_count": 0,
			"white_count": 0
		}
	]

static func get_black_cards() -> Array:
	# Retorna cartas baseado no idioma (simplificado por enquanto)
	# Idealmente, acessaria LocalizationManager, mas como é estático,
	# vamos checar se existe a classe global ou usar padrao
	return BLACK_CARDS_BR.duplicate()

static func get_white_cards() -> Array:
	return WHITE_CARDS_BR.duplicate()

# ============================================
# INSTRUCOES DE PREENCHIMENTO
# ============================================
# Substitua os exemplos abaixo com as cartas reais.
# Mantenha o formato de string entre aspas.
# Para cartas pretas (perguntas), use "____" para indicar o espaco em branco.

# ============================================
# CARTAS BRASILEIRAS (PT-BR EXCLUSIVO)
# ============================================
# Estas cartas aparecem APENAS quando o idioma e Portugues.
const BLACK_CARDS_BR = [
	"Durante sua infância, Salvador Dali fez centenas de pinturas de ____.",
	"O que é mais emo?",
	"É uma pena que as crianças hoje em dia estão todas envolvidas em ____.",
	"Em 1000 anos, quando dinheiro de papel for apenas uma lembrança distante, ____ será nossa moeda.",
	"A CBF proíbe ____ por proporcionar vantagem desleal ao jogador.",
	"Qual é o prazer proibido do Batman?",
	"Professora, não pude terminar a lição de casa por causa de ____.",
	"O que eu trouxe do paraguai?",
	"Papai, por que mamãe está chorando?",
	"Vem aí o novo livro de J. K. Rowlling, Harry Potter e a Câmara de ____?",
	"Tem um APP para ____.",
	"A Infraero agora proíbe ____ em aviões.",
	"Enquanto EUA e URSS competiam na corrida espacial, o Brasil investia pesado em ____.",
	"____: é impossível comer um só!",
	"Qual meu poder secreto?",
	"Qual é a dieta do momento?",
	"O que Vin Diesel comeu no jantar?",
	"Quando Faraó se manteve irredutível, Moisés invocou uma praga de ____.",
	"Como estou mantendo minha atual relação amorosa?",
	"Dizem que no Carandiru se trocava 10 maços de cigarro por ____.",
	"Qual é o cúmulo da porquice?",
	"O Museu de Arte Moderna acabou de lançar uma exibição interativa sobre ____.",
	"No novo filme da Disney, Hanna Montana enfrenta ____ pela primeira vez.",
	"Depois do terremoto, Dilma levou ____ para o Haití.",
	"No próximo Natal, Papai Noel dará ____ para a criança que se comportar.",
	"A vida dos índios mudou para sempre quando os portugueses lhes apresentaram ____.",
	"O novo programa do governo para crianças carentes é ____.",
	"Talvez ela tenha nascido assim, ou talvez ela seja ____.",
	"Em seus momentos finais, Michael Jackson pensou em ____.",
	"Brancos gostam de ____.",
	"Porque eu estou todo dolorido?",
	"Ligue já para 0800-0000 e peça o seu ____.",
	"Luciano Huck, realize meu sonho que é ____.",
	"____: Bom até a última gota.",
	"____ que se melhora com a idade?",
	"Um jantar a luz de velas seria incompleto se ____.",
	"O passeio escolar foi um fiasco devido a ____.",
	"Quando for presidente, criarei o ministério de ____.",
	"O que eu preciso trazer do passado para convencer que eu sou um mágico poderoso?",
	"____ é o melhor amigo de uma mulher.",
	"O que meus pais estão escondendo de mim?",
	"Tenho 99 problemas, mas ____ não é um deles.",
	"O novo reality da Record tem 12 celebridades decadentes vivendo com um ____.",
	"O que minha vó acharia perturbador, mas ao mesmo tempo elegante?",
	"Durante o sexo, costumo pensar sobre ____.",
	"O que causou o fim do meu último namoro?",
	"Que som é esse?",
	"É assim que eu quero morrer.",
	"Estou grudento por causa de ____.",
	"O próximo brinde do Mc Lanche feliz é ____.",
	"No céu tem ____ à vontade.",
	"Não sei quais serão as armas da terceira guerra mundial, mas a Quarta guerra será com ____.",
	"Não consigo dormir a noite por causa de ____.",
	"Para conseguir sexo grátis eu só preciso de ____.",
	"O que ajuda o Obama a relaxar?",
	"____. Testado pelas crianças, aprovado pelas mães.",
	"Assim acaba o Mundo. Não com uma explosão, mas com ____.",
	"Chega no Brasil o novo musical da Broadway chamado ____.",
	"Antropólogos recentemente descobriram um nova tribo primitiva que cultua ____.",
	"Antes de matá-lo, Mr. Bond, preciso lhe mostrar ____.",
	"Estudos mostram que os ratos de laboratório são mais efetivos quando são expostos a ____.",
	"Daqui a pouco na SporTV 3, campeonato mundial de ____.",
	"Quando for bilionário, organizarei uma festa para comemorar os ____.",
	"Guerra! Serve para ____.",
	"____ me deixa com gases incontroláveis.",
	"Durante o sexo, ____.",
	"Idosos têm cheiro de ____.",
	"Os EUA, por meio de aviões, lançou ____ às crianças do Afeganistão.",
	"Hoje eu bebi para esquecer ____.",
	"O que vou deixar de fazer na quaresma?",
	"O que o técnico Tite prefere?",
	"A ciência está reconhecendo os poderes curativos da ____.",
	"Estava comendo ____ e encontrei ____ no meu Yakisoba.",
	"Toca aqui irmão!",
	"Dilma gosta de comer ____ recheado com ____.",
	"E o prêmio do ano vai para ____.",
	"Passo 1: ____. Passo 2: ____. Passo 3: Lucrar.",
	"É verdade, eu matei ____.",
	"Para meu próximo truque, vou tirar ____ da minha ____.",
	"E sabe como foi? com uma ____.",
	"Quando usei crack e estava muito louco, ____ se transformou em ____.",
	"____ é um caminho sem volta que leva para ____.",
	"Em um mundo devastado por ____, o único conforto é ____.",
	"Eu realmente nunca entendi ____ até encontrar ____.",
	"Faça um poema de 3 versos (haiku).",
	"9 entre 10 médicos dizem que ____ 2 vezes ao dia previne câncer.",
	"Um vidente disse que minha vida será cheia de ____.",
	"Uma nova prática médica envolve colocar ____ dentro de ____.",
	"Eu achei ____ perdido embaixo do sofá.",
	"O novo Iphone é tão inovador que agora é possível ____ com ele.",
	"É muito ruim quando você abre a geladeira e tudo o que tem para comer é ____.",
	"Quando eu era criança, sonhava em ser ____.",
	"É mais desagradável do que ____ em uma reunião.",
	"A nova moda deste verão é ____.",
	"Rumores dizem que o próximo Windows vai vir com ____.",
	"O que eu gosto mais do meu emprego é ____.",
	"De acordo com uma superstição romena, você deve ____ antes de ir para cama, senão acontece ____ com você.",
	"Mantenha seus amigos perto, mas seus ____ mais perto ainda.",
	"O que fez eu pegar aids?",
	"Eu daria tudo para ficar 10 minutos sozinho com ____.",
	"Todas as crianças maneiras estão fazendo isso.",
	"O ____ ia na fazenda tinha ____ e ____ ia - ô.",
	"E a moral da estória é ____.",
    "Te amar é fácil, porque você é ____."
]

const WHITE_CARDS_BR = [
"Uma maldição cigana.",
	"Um momento de silêncio.",
	"Uma festa onde só tem macho.",
	"Um policial honesto sem nada a perder.",
	"A fome.",
	"Bactéria carnívora.",
	"Cobras voadoras taradas.",
	"Cagar para o Terceiro Mundo.",
	"Mandar nudes no Whatsapp.",
	"Operação de troca de sexo.",
	"Estrelas pornôs.",
	"Estuprar e Roubar.",
	"72 virgens.",
	"Fuzilamento.",
	"Um paradoxo de viagem no tempo.",
	"Culinária Mexicana.",
	"Bijuterias.",
	"Consultores.",
	"Dúvidas pra caralho.",
	"Problemas com o pai na infância.",
	"Cotas raciais.",
	"Passar a perna em alguém.",
	"O ex-presidente Lula.",
	"Nu frontal completo.",
	"Injeções hormonais.",
	"Botar um ovo.",
	"Assistir Discovery Kids Pelado(a).",
	"Fingir que se importa.",
	"Pagar mico em público.",
	"Compartilhar Agulhas.",
	"Meleca de nariz.",
	"A inevitável destruição do universo.",
	"O milagre do nascimento.",
	"Apocalipse.",
	"Pegar geral.",
	"Classe média sofre.",
	"Deveres de marido.",
	"Roberval, o ladrão de chocolates.",
	"Desodorante AXE.",
	"O sangue de Cristo.",
	"Terrível acidente com depilação a laser.",
	"BATMAN!!!",
	"Agricultura.",
	"Um retardado fortão.",
	"Seleção Natural.",
	"Aborto clandestino.",
	"Comer todos os doces antes da feira beneficente.",
	"O nariz do Luciano Huck.",
	"World of Warcraft.",
	"Furar o olho do amigo.",
	"Obesidade.",
	"Vídeo Homoerótico com jogadores de vôlei.",
	"Tétano.",
	"Dança do acasalamento.",
	"Prender o saco no zíper.",
	"Luan Santana",
	"Tirar a camisa.",
	"Buffet completo por R$8,00",
	"Misto quente.",
	"Esmegma.",
	"Feijoada.",
	"Ataque de Velociraptors.",
	"Alcoolismo.",
	"Um senhor da terceira idade andando de patins.",
	"Um sorvetão de Itu.",
	"Preliminares meia-boca.",
	"Um abraço dos ursinhos carinhosos.",
	"Auto-piedade.",
	"A Bíblia Sagrada.",
	"Beber, cair e Levantar.",
	"Crianças com coleiras.",
	"Pornô Alemão Sado-Masô.",
	"Pegar fogo.",
	"Gravidez na Adolescência.",
	"Gandhi.",
	"Deixar uma mensagem de voz bizarra.",
	"Manter a ereção por mais de 4 horas.",
	"Cruzado de Direita.",
	"Minha genitália.",
	"Atendentes de Telemarketing.",
	"Clínica de aborto.",
	"Ciência.",
	"Disque-sexo.",
	"Aves que não voam.",
	"Uma boa cheirada.",
	"Afogamento simulado.",
	"Café da manhã balanceado.",
	"Escolas públicas.",
	"Roubar doce de criança.",
	"Criança Esperança.",
	"Uma passada de mão dentro do metrô.",
	"Recados em Post-it passivo-agressivos.",
	"A equipe de ginástica artística chinesa.",
	"Mude para a Porto Seguro®.",
	"Mijar um pouco nas calças.",
	"Video caseiro da Ana Maria Braga criticando a comida.",
	"Polução noturna.",
	"Os judeus.",
	"Minha bunda.",
	"Coxas poderosas.",
	"Flertar com Idosos.",
	"Pato Purific®, confie no bico do pato!",
	"Uma passada de mão na parte interna da coxa.",
	"Tensão sexual.",
	"O fruto proibido.",
	"Esqueleto do He-Man.",
	"Churrasco na lage.",
	"Ser rico.",
	"Doce, doce vingança.",
	"Petistas.",
	"Um jumento com gases.",
	"Natalie Portman.",
	"Pegadinha do malandro!",
	"Pilotos Kamikazes.",
	"Antônio Fagundes.",
	"Fazer Programa Gay.",
	"Servente de Pedreiro.",
	"Briga de Galo.",
	"Coroinhas.",
	"O garoto propaganda das Casas Bahia®.",
	"Ereção involuntária em público.",
	"Fazer a coisa certa.",
	"Amostras Grátis.",
	"O jeitinho brasileiro.",
	"Fazer tempestade num copo d'água.",
	"Amamentação.",
	"Paz Mundial.",
	"RoboCop.",
	"Malandragem.",
	"Justin Bieber.",
	"Oompa-Loompas.",
	"Funk Ostentação.",
	"Puberdade.",
	"Axé music.",
	"Fantasmas.",
	"Masturbação feminina.",
	"Implante de silicone assimétrico.",
	"Dinheiro na cueca.",
	"Danoninho®.",
	"Morrer sozinho e com dor.",
	"Policial corrupto.",
	"Flanelinha.",
	"Pré-adolescentes.",
	"Corte de cabelo bizarro.",
	"Segurar o riso ao ouvir México x Peru.",
	"Twittar.",
	"Darth Vader.",
	"Uma punheta mal batida.",
	"Exatamente o que você esperava.",
	"Arrotar e acabar vomitando no chão.",
	"Gardenal.",
	"Células-tronco.",
	"Um decote bem gostoso.",
	"Sexo entre pandas.",
	"Herpes labial.",
	"Mão naquilo, aquilo na mão.",
	"Um mímico tendo AVC.",
	"Lobotomia com picador de gelo.",
	"Esperma de baleia.",
	"Incesto.",
	"Anderson Silva.",
	"Tom Cruise.",
	"Moradores de rua.",
	"O Pac-Man gozando incontrolavelmente.",
	"Deus.",
	"Lavar bem as dobrinhas.",
	"Zoofilia.",
	"Emoções.",
	"Lamber a comida para dizer que é sua.",
	"Cerveja quente.",
	"Queimar mendigo.",
	"A Placenta.",
	"Amizade colorida.",
	"Pintura com os dedos.",
	"Cheiro de gente velha.",
	"Morrer de disenteria.",
	"Meus demônios internos.",
	"Pistola d'água cheia de xixi de gato.",
	"Paulo Coelho.",
	"Dormir de conchinha.",
	"A erva.",
	"Ronaldo Fenômeno.",
	"Fogo amigo.",
	"Regina Casé.",
	"Uma festa de aniversário fracassada.",
	"Uma mulata safada.",
	"Olimpíadas de Matemática.",
	"Um Pônei.",
	"Pablo Vittar.",
	"Cavalgar em direção ao pôr do sol.",
	"Filme brasileiro sobre favelas.",
	"Cabelo Pixaim.",
	"Destruição Mútua Assegurada (MAD).",
	"Pedófilos.",
	"Fungos.",
	"Roubo de Túmulos.",
	"Gente pobre.",
	"Comer o último biscoito do pacote.",
	"O doce veneno do escorpião.",
	"Catapultas.",
	"Forró rala-coxa.",
	"A Força.",
	"Chicote de toalha.",
	"Design inteligente.",
	"Língua solta.",
	"AIDS.",
	"Big Brother Brasil.",
	"Dilma Rousseff.",
	"Fotos de seios.",
	"Os Vingadores®.",
	"Ficar muito chapado.",
	"Cientologia.",
	"Inveja do pênis do próximo no banheiro público.",
	"Cura Gay.",
	"Dois anões cagando num balde.",
	"Os Black Blocs.",
	"Metanfetamina.",
	"Escravidão.",
	"A carreira de ator do Michael Jordan.",
	"Fazer um favor esperando algo em troca.",
	"Ir a um motel.",
	"Buda.",
	"Não aceitar doce de estranhos.",
	"Periguete.",
	"Hentai em baixa resolução.",
	"Um brinquedo Bop It®.",
	"Policiais da UPP.",
	"Uma vida triste.",
	"Racismo.",
	"Arremesso de anão.",
	"Tesouro no fim do Arco-Íris.",
	"Um macaco fumando charuto.",
	"Inundação.",
	"O testículo perdido do Lance Armstrong.",
	"Zoar alguém.",
	"Terroristas.",
	"Faustão.",
	"Atitude.",
	"Flash Mob.",
	"Lepra.",
	"Sexo no banheiro de avião.",
	"Ficar de faróis acesos.",
	"Coração de criança.",
	"Filhotes de cachorro.",
	"Acordar seminú no estacionamento do McDonald's®.",
	"Poder.",
	"Dentadura de doce Fini®.",
	"A vagina da Cláudia Ohana.",
	"Ouvir atentamente.",
	"Limpeza intestinal.",
	"Os escravos de Jó jogavam caxangá.",
	"Mão invisível.",
	"Se guardando para o casamento.",
	"Repassar um presente.",
	"Atitude estúpida.",
	"Auto-canibalismo.",
	"Euphoria® por Calvin Klein.",
	"Pênis brocha.",
	"Minha coleção de brinquedos eróticos.",
	"Papa.",
	"Pessoas brancas.",
	"Pornografia envolvendo tentáculos.",
	"Boris Casoy espirrando e pedindo desculpas.",
	"Gel de cabelo em excesso.",
	"Ritual Maia.",
	"Carisma.",
	"Patinação no gelo com parceiro do mesmo sexo.",
	"Corte de cabelo pubiano.",
	"Trapacear nos jogos para-olímpicos.",
	"Sean Penn.",
	"Nickelback.",
	"Cagando e andando.",
	"Menstruação.",
	"Surpresa desagradável.",
	"Violação dos mais básicos direitos humanos.",
	"PEDE PRA SAIR!!!",
	"SexyHot.",
	"Ser fabuloso.",
	"Necrofilia.",
	"Centauros.",
	"Mundo de Beakman.",
	"Pessoas negras.",
	"Abrir a porta do carro para a mulher.",
	"Biscoito Passatempo®.",
	"Garotas de Programas.",
	"Retardados.",
	"Órfãos.",
	"Call of Duty.",
	"Cagar dolorosamente.",
	"Outro maldito filme sobre vampiros.",
	"Mola Maluca.",
	"O verdadeiro significado do Natal.",
	"Estrogênio.",
	"O nordeste.",
	"Pizza gelada no café da manhã.",
	"Aquele negócio que eletrocuta seu abdomen.",
	"Cálculo renal.",
	"Clareamento anal.",
	"Michael Jackson.",
	"Melhorias cibernéticas.",
	"Caras que não ligam no dia seguinte.",
	"Lençol de motel.",
	"Masturbação.",
	"Cantadas de pedreiro.",
	"Peido de Vagina.",
	"Esconder uma ereção.",
	"Calcinhas comestíveis.",
	"Viagra®",
	"Idoso tomando Viagra®.",
	"Maomé (que seja louvado seu nome)",
	"Sexo surpresa!",
	"Promoção da semana do Subway®.",
	"Forever alone.",
	"Cleptomaníaco.",
	"Facadas múltiplas.",
	"Se cagar todo.",
	"Abuso infantil.",
	"Contas anais.",
	"Casal que gosta de swing.",
	"Coito interrompido.",
	"Robert Downey Jr.",
	"Anabolizantes para cavalo.",
	"Um pentelho rebelde.",
	"Tomar uma enrabada.",
	"Um chapéu de desfile de moda.",
	"Repúblicas de Universidade.",
	"Alimentar a Adele.",
	"Mao Tsé-Tung.",
	"Um casal de anões.",
	"Ensinar um robô a amar.",
	"O rei do camarote.",
	"Umas sala cheia de cadáveres.",
	"A bebida Lactobacilos loucos.",
	"Vestir a cueca ao avesso para não lavar.",
	"Raio da Morte.",
	"Teto de vidro.",
	"Um congelador cheio de órgãos.",
	"O sonho americano.",
	"Barriga de Chopp.",
	"Um peido molhado.",
	"A cabeça do meu pênis.",
	"Pegar de volta o que foi emprestado.",
	"Solo de Saxofone.",
	"Bebês dançarinos.",
	"Argentinos",
	"Um feto.",
	"Atirar para o alto enquanto come uma cabra no barranco.",
	"Michel Temer.",
	"Amputados.",
	"Emmanuele em Veneza.",
	"Meu status de relacionamento.",
	"Caetano Veloso.",
	"Abelhas?",
	"Paródia pornô de Harry Potter.",
	"Faculdade.",
	"Ficar bêbado com Cepacol®.",
	"Nazistas.",
	"10 gramas de heroína colombiana.",
	"Brincadeira de Morto-Vivo.",
	"Fala muito!",
	"Stephen Hawking falando palavrão.",
	"Luta de dedão.",
	"Motosserra.",
	"Pais mortos.",
	"Questões racistas em vestibulares.",
	"Nicholas Cage.",
	"Miss Gay Universo.",
	"Explosões.",
	"Cheirar cola.",
	"Repressão.",
	"Boa noite cinderela.",
	"Minha vagina.",
	"Biquini fio cheiroso.",
	"Serial Killer.",
	"Dar 110%",
	"Sua alteza, rainha Elizabeth",
	"A linha vermelha.",
	"Ser marginalizado.",
	"Goblins.",
	"Esperança.",
	"Martin Luther King Jr.",
	"Um micro-pênis.",
	"Minha alma.",
	"A maior confusão.",
	"Vikings.",
	"Gostosas.",
	"Complexo de Édipo.",
	"Gansos.",
	"Aquecimento global.",
	"Música New Age.",
	"HotPocket®.",
	"Fazer bico.",
	"Atropelamento.",
	"Voto das mulheres.",
	"Uma camisinha defeituosa.",
	"Sessão da tarde.",
	"Crianças africanas.",
	"Matar todo mundo dentro do cinema.",
	"Barack Obama.",
	"Asiáticos que não são bons em matemática.",
	"Velhinhos japoneses.",
	"Troca de gentilezas.",
	"Perder a virgindade.",
	"Arnold Schwarzenegger.",
	"Homosexual.",
	"Abrir o mar vermelho.",
	"Pingado com Pão na chapa.",
	"Boquete no carro.",
	"Barriga Tanquinho.",
	"Um leão de zoológico deprimido.",
	"Saco de feijões mágicos.",
	"Escolhas erradas.",
	"Minha vida sexual",
	"Auchwitz.",
	"Uma tartaruga mordendo a cabeça do seu pênis.",
	"O Big Bang.",
	"Uma detonação termonuclear.",
	"Minas terrestres.",
	"Clitóris.",
	"Amigos que comem toda a comida.",
	"Músicas com bodes cantando.",
	"Sushi erótico.",
	"Se masturbar vendo a Misty do Pokémon.",
	"Carne humana.",
	"Piadas sobre o holocausto na hora errada.",
	"A voz do Cid Moreira.",
	"Um tempo só para mim.",
	"Problemas pra cacete.",
	"Mulheres de comercial de cerveja.",
	"Pedra, papel e tesoura.",
	"Estórias de pescador.",
	"Aparelho de aumento de pênis.",
	"Um mágico fracassado.",
	"Piercing genital.",
	"Travestis que são iguais a mulheres.",
	"Briga de travesseiro sensual.",
	"As bolas do saco.",
	"Vovó.",
	"Fricção.",
	"Ser chato pra caralho.",
	"Colocar armadilhas em casa contra assaltantes.",
	"Trepar.",
	"Furacão Katrina.",
	"Nanny People.",
	"Morrer.",
	"A tolice dos homens.",
	"Homens.",
	"Evangélicos.",
	"Ovos de pterodáctilo.",
	"Dinâmica de grupo.",
	"William Bonner.",
	"Cartas contra a Humanidade.",
	"Ter medo de você mesmo.",
	"Lady Gaga.",
	"Entregador de Pizza.",
	"Boca suja.",
	"Mal hálito.",
	"Vadia, cadê minha grana?",
	"Motoristas de ônibus.",
	"Um mal pressentimento.",
	"Pikachu.",
	"Não ser pego.",
	"Estar 'apenas um pouco grávida'",
	"Praticar posições do Kama Sutra.",
	"Os caça fantasmas!",
	"Ficar em segundo numa competição de boquete.",
	"Mandar SMS bêbado.",
	"Pirocóptero giratório.",
	"Colocar pimenta Tabasco na uretra.",
	"2 girls 1 cup.",
	"1 trilhão de dólares.",
	"50 tons de cinza.",
	"Cortar seu pau fora.",
	"Um velho sensualizando de forma bizarra.",
	"Paris Hilton.",
	"Uma caixa de Choquito®.",
	"Desafiar as leis da física.",
	"Um Bar-Mitzvah.",
	"X-Vídeos.",
	"A cidade de Pelotas.",
	"Orgia de Pinguins.",
	"Diarréia.",
	"Um tapa afeminado.",
	"Implante peniano.",
	"Pessoas que fedem igual as próprias meias.",
	"O buraco negro.",
	"Derrubar seu iPhone® na privada.",
	"Banheiros Públicos.",
	"Editar o Wikipedia para ganhar uma discussão.",
	"Jô Soares.",
	"Uma oportunista.",
	"Uma criança obesa.",
	"Um vibrador da Hello Kitty®.",
	"Feministas com bigode.",
	"Descobrir que seu marido é gay.",
	"Pepe, já tirei a vela!",
	"O gosto do sêmen.",
	"Brincar de médico.",
	"Um pacote de Mentos e 2 litros de Coca-Cola Zero®.",
	"Vai se foder.",
	"Um bexigão cheio de escorpiões.",
	"Trepar enquanto ouve Bee Gees.",
	"Aquele tio racista.",
	"Pornô Gay do Crepúsculo.",
	"Ruivos.",
	"Deus odeia você.",
	"Sexo entre amputados.",
	"Hitler's churrascaria.",
	"Fusca azul!",
	"Eu amo você.",
	"Ser estuprado por um jumento.",
	"Bin Laden.",
	"Zo-zo-zo-ar os Ga-ga-ga-ga-gos.",
	"Tetas de homens.",
	"Charlie Sheen.",
	"Mulheres.",
	"Chuck Norris.",
	"Transar imitando a voz do Mickey Mouse.",
	"Velhos histéricos fazendo sexo.",
	"A cena da morte do Mufasa.",
	"Não fazer sexo.",
	"Velcro.",
	"Uma apresentação em PowerPoint.",
	"Arrotar, espirrar e gozar ao mesmo tempo.",
	"Viver no barril do Chaves.",
	"Eu.",
	"Dupla penetração.",
	"Um galão de 55 litros de lubrificante.",
	"Fazer um amigo.",
	"Meu primeiro assassinato.",
	"O corpo humano.",
	"Seios que parecem ovos fritos.",
	"Ser muito bom no sexo.",
	"Kid Bengala.",
	"Overdose.",
	"As nádegas do meu avô.",
	"Procurando o Wally.",
	"Google.",
	"Usuários de Orkut.",
	# === CARTAS PESADAS ===
	"Abortar com um cabide.",
	"Fazer sexo com o cadáver da avó.",
	"Crianças em jaulas na fronteira.",
	"O cheiro de uma fossa de Auschwitz.",
	"Comer o próprio filho para sobreviver.",
	"Um padre ejaculando na hóstia.",
	"Torturar animais por prazer.",
	"Tráfico de órgãos de crianças.",
	"O 11 de setembro, só que mais divertido.",
	"Usar síndrome de down como xingamento.",
	"Fazer um snuff film caseiro.",
	"Câncer terminal em uma criança de 5 anos.",
	"Escravizar deficientes mentais.",
	"Comer o clitóris da própria mãe.",
	"Matar toda a família e culpar o cachorro.",
	"Vender a irmã mais nova para um bordel.",
	"Um vídeo de execução do ISIS com música de fundo.",
	"Dar laxante para idosos em asilo.",
	"Uma gangbang com a Madre Teresa.",
	"Assistir pornô de anões enquanto mama a própria mãe.",
	"Usar um feto como fantoche.",
	"Holocausto 2: Electric Boogaloo.",
	"Sequestrar crianças para vender no Mercado Livre.",
	"Fazer um colar de clitóris.",
	"Nazismo, mas para gordos.",
	"Transar com o buraco da traqueostomia.",
	"Uma orgia em Chernobyl.",
	"Enfiar um crucifixo no cu do Papa.",
	"Queimar órfãos para aquecer a casa.",
	"Beber água de enchente com cadáveres.",
	"Um campo de concentração, mas divertido.",
	"Colocar veneno na merenda escolar.",
	"Genocídio étnico como team building.",
	"Fazer um churrasco com carne de mendigo.",
	# === MAIS CARTAS PESADAS ===
	"Vender o rim da sogra no OLX.",
	"Eutanásia involuntária.",
	"Um orfanato pegando fogo.",
	"Comer cocô achando que era brigadeiro.",
	"Teste de gravidez positivo aos 12 anos.",
	"Atropelar ciclistas por esporte.",
	"Canibalismo entre amigos.",
	"Mandar a avó de presente pro Talibã.",
	"Um tiroteio em escola americana.",
	"AIDS como presente de casamento.",
	"Empurrar cadeirante escada abaixo.",
	"Vender crack em creche.",
	"Doar sangue contaminado.",
	"Jogar idosos da ponte.",
	"Falsificar exame de câncer.",
	"Roubar esmola de cego.",
	"Provocar aborto espontâneo com chute.",
	"Usar deficiente como saco de pancadas."
	]

# ============================================
# CARTAS INTERNACIONAIS (INGLES)
# ============================================
# Estas cartas aparecem APENAS quando o idioma e Ingles.
const BLACK_CARDS_EN = [
	"Why can't I sleep at night?",
	"I got 99 problems but ____ ain't one.",
	"What's the next Happy Meal toy?",
	"Daddy, why is mommy crying?",
	"in the new Disney movie, Hannah Montana struggles with: ____.",
	"Instead of coal, Santa now gives the bad children: ____.",
	"What is Batman's guilty pleasure?",
	"Man, this is gonna be the best ____ ever!",
	"TSA guidelines now prohibit ____ on airplanes.",
	"What ended my last relationship?",
	"War! What is it good for?",
	"What does Dick Cheney prefer to waterboarding?",
	"____. That's how I want to die.",
	"What's that smell?",
	"I drink to forget: ____.",
	"New from Mattel: Barbie's ____ accessory.",
	"What helps Obama unwind?",
	"During sex, I like to think about: ____.",
	"What did I bring back from Mexico?",
	"When I am Prime Minister, I will create the Ministry of: ____.",
	"What's the crusty stuff on my couch?",
	"Next on MTV: Pimp My ____.",
	"Step 1: ____. Step 2: ____. Step 3: Profit.",
	"They said we were crazy. They said we couldn't put ____ inside of ____. They were wrong.",
	"Sorry everyone, I just ____.",
	"Life for American Indians was forever changed when the White Man introduced them to: ____.",
	"What's the most emo?",
	"Coming to Broadway this season, ____: The Musical.",
	"The class field trip was completely ruined by: ____.",
	"In a world ravaged by ____, our only solace is ____.",
	"I never truly understood ____ until I encountered ____.",
	"Rumor has it that Vladimir Putin's favorite dish is: ____.",
	"What are my parents hiding from me?",
	"____. Good to the last drop.",
	"What did the US military airdrop to the children of Afghanistan?",
	"What am I giving up for Lent?",
	"In M. Night Shyamalan's new movie, Bruce Willis discovers that he had really been ____ all along.",
	"How did I lose my virginity?",
	"The blind date was going horribly until we discovered our shared love for: ____.",
	"____. It's a trap!",
	"A romantic, candlelit dinner would be incomplete without: ____.",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on: ____.",
	"____. Betcha can't have just one!",
	"It's a pity that kids these days are all getting involved with: ____.",
	"What totally destroyed my asshole?",
	"My country, 'tis of thee, sweet land of: ____.",
	"What gives me uncontrollable gas?",
	"The new Bible features a hip, modern Jesus who forgives: ____.",
	"What is the secret to a happy marriage?",
	"My gym teacher got fired for adding ____ to the obstacle course.",
	"The Pope has officially canonized the patron saint of: ____.",
	"____. High five, bro.",
	"I'm sorry, Professor, but I couldn't complete my homework because of: ____.",
	"What's there a ton of in heaven?",
	"White people like ____.",
	"Why am I sticky?",
	"Today on Maury: \"Help! My son is ____!\"",
	"____. Kid tested, mother approved.",
	"Before I kill you, Mr. Bond, I must show you: ____.",
	"What's the new fad diet?",
	"Major League Baseball has banned ____ for giving players an unfair advantage.",
	"If God didn't want us to enjoy ____, he wouldn't have given us ____.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with: ____.",
	"What's the gift that keeps on giving?",
	"In the beginning, there was ____. And the Lord said, \"Let there be ____.\"",
	"New from Pfizer: Viagra for: ____.",
	"The healing process began when I joined a support group for victims of: ____.",
	"The Exorcist of Emily Rose was actually caused by: ____.",
	"What is the worst thing you can find in a Chinese food buffet?",
	"____. The breakfast of champions.",
	"When I'm in prison, I'll hide ____ inside my anal cavity.",
	"The internet is for: ____.",
	"Behold, the Four Horsemen of the Apocalypse! War, Famine, Pestilence, and: ____.",
	"To produce the perfect erection, you must use: ____.",
	"What makes me projectile vomit?",
	"Science will never explain the origin of: ____.",
	"During his midlife crisis, my dad got into: ____.",
	"Wake up, America. The terrorists have won. They have: ____.",
	"In his final moments, Michael Jackson mumbled about: ____.",
	"____. It's what's for dinner.",
	"Only two things in life are certain: death and: ____.",
	"Who is the most dangerous man in the world?",
	"The CIA is currently monitoring: ____.",
	"What's the most annoying thing about my coworkers?",
	"The best pickup line starts with: ____.",
	"My therapist says I have an unhealthy obsession with: ____.",
	"The prophecy foretold that the world would end with: ____.",
	"What's hiding under my bed?",
	"I finally found a use for: ____.",
	"____. Because I'm worth it.",
	"The only thing that gets me hard anymore is: ____.",
	"What is the ultimate forbidden fruit?",
	"My autobiography is titled \"____: A Love Story.\"",
	"The Nobel Peace Prize goes to: ____.",
	"What happens in Vegas stays in Vegas, except for: ____.",
	"Why did the chicken cross the road?",
	"____. Not even once.",
	"Who let the dogs out?",
	"Click here for hot singles in your area looking for: ____.",
	"The secret ingredient in Grandma's cookies is: ____."
]

const WHITE_CARDS_EN = [
	"A big black dick.",
	"A bleached asshole.",
	"A brain tumor.",
	"A bucket of fish heads.",
	"A can of whoop-ass.",
	"A cooler full of organs.",
	"A corpse.",
	"A death ray.",
	"A defective condom.",
	"A disappointing birthday party.",
	"A falcon with a cap on its head.",
	"A fetus.",
	"A foul mouth.",
	"A gassy antelope.",
	"A gentle caress of the inner thigh.",
	"A good sniff.",
	"A Gypsy curse.",
	"A homoerotic volleyball montage.",
	"A hot mess.",
	"A lifetime of sadness.",
	"A look-see.",
	"A man on the brink of orgasm.",
	"A mating display.",
	"A micropenis.",
	"A middle-aged man on roller skates.",
	"A mime having a stroke.",
	"A monkey smoking a cigar.",
	"A mopey zoo lion.",
	"A murder most foul.",
	"A pyramid of severed heads.",
	"A really cool hat.",
	"A robust mongoloid.",
	"A sad handjob.",
	"A salty surprise.",
	"A saxophone solo.",
	"A sea of troubles.",
	"A snapping turtle biting the tip of your penis.",
	"A stray pube.",
	"A Super Soaker™ full of cat pee.",
	"A thermonuclear detonation.",
	"A time travel paradox.",
	"A tiny horse.",
	"A windmill full of corpses.",
	"A woman's perspective.",
	"Abstinence.",
	"Academy Award winner Meryl Streep.",
	"Accepting the way things are.",
	"Active listening.",
	"Adderall™.",
	"Adult Diapers.",
	"African children.",
	"Agriculture.",
	"AIDS.",
	"Alcoholism.",
	"All-you-can-eat shrimp for $4.99.",
	"Altar boys.",
	"American Gladiators.",
	"Amputees.",
	"Anal beads.",
	"Anal fissures.",
	"Angelina Jolie.",
	"Another goddamn vampire movie.",
	"Arnold Schwarzenegger.",
	"Asians who aren't good at math.",
	"Assless chaps.",
	"Attitude.",
	"Auschwitz.",
	"Authentic Mexican cuisine.",
	"Autocannibalism.",
	"AXE Body Spray.",
	"Balls.",
	"Barack Obama.",
	"Basic human decency.",
	"Batman.",
	"Battling a 100-foot penguin.",
	"Bear attacks.",
	"Beef curtains.",
	"Being a dick to children.",
	"Being a motherfucking sorcerer.",
	"Being fabulous.",
	"Being marginalized.",
	"Being on fire.",
	"Being rich.",
	"Bill Nye the Science Guy.",
	"Bingeing and purging.",
	"Bitches.",
	"Black people.",
	"Bling.",
	"Blood farts.",
	"Blowjobs.",
	"Boogers.",
	"Boris the Soviet Love Hammer.",
	"Bosnian chicken farmers.",
	"Breaking out into song and dance.",
	"Britney Spears at 55.",
	"Brown people.",
	"Bubble butt bottom boys.",
	"Bullshit.",
	"Cards Against Humanity.",
	"Catapults.",
	"Centaurs.",
	"Chainsaws for hands.",
	"Charisma.",
	"Cheating in the Special Olympics.",
	"Child abuse.",
	"Child beauty pageants.",
	"Children on leashes.",
	"Chivalry.",
	"Christopher Walken.",
	"Civilian casualties.",
	"Clams.",
	"Classist undertones.",
	"Cleaning out your insides with a bottle brush.",
	"Coat hanger abortions.",
	"Cockfights.",
	"College.",
	"Concealing a boner.",
	"Consultants.",
	"Copping a feel.",
	"Coughing into a vagina.",
	"Count Chocula.",
	"Crippling debt.",
	"Crystal meth.",
	"Cuddling.",
	"Customer service representatives.",
	"Cybernetic enhancements.",
	"Daddy issues.",
	"Daddy's belt.",
	"Dancing with a broom.",
	"Dark and mysterious forces.",
	"Darth Vader.",
	"Date rape.",
	"Dead babies.",
	"Dead parents.",
	"Death by Chow Chow.",
	"Deflowering the princess.",
	"Dental dams.",
	"Destroying the evidence.",
	"Dick fingers.",
	"Dining with cardboard cutouts of the cast of \"Friends.\"",
	"Dirty diapers.",
	"Disco fever.",
	"Doin' it in the butt.",
	"Doing the right thing.",
	"Domino's™ Oreo™ Dessert Pizza.",
	"Donald Trump.",
	"Double penetration.",
	"Drinking alone.",
	"Dropping a chandelier on your enemies and riding the rope up.",
	"Dry heaving.",
	"Dwarf tossing.",
	"Dying.",
	"Eating all of the cookies before the AIDS bake-sale.",
	"Eating an albino.",
	"Eating the last known bison.",
	"Edible underpants.",
	"Elderly Japanese men.",
	"Electric fence.",
	"Embryonic stem cells.",
	"Emeril Lagasse.",
	"Emma Watson.",
	"Emotions.",
	"Enormous Scandinavian women.",
	"Erectile dysfunction.",
	"Estrogen.",
	"Ethnic cleansing.",
	"Eugenics.",
	"Euphoria™ by Calvin Klein.",
	"Exactly what you'd expect.",
	"Exchanging pleasantries.",
	"Existing.",
	"Expecting a burp and vomiting.",
	"Explosions.",
	"Fabricating statistics.",
	"Famine.",
	"Fancy Feast.",
	"Farting and walking away.",
	"Fear of self.",
	"Feeding Rosie O'Donnell.",
	"Fetal alcohol syndrome.",
	"Fiery poops.",
	"Figgy pudding.",
	"Finding a skeleton.",
	"Finding Waldo.",
	"Finger painting.",
	"Fingering.",
	"Firing a rifle into the air while balls deep in a squealing hog.",
	"Five-Dollar Footlongs™.",
	"Flash floods.",
	"Flesh-eating bacteria.",
	"Flightless birds.",
	"Flying sex snakes.",
	"Foreskin.",
	"Forgetting the Alamo.",
	"Former President George W. Bush.",
	"Free samples.",
	"Friction.",
	"Friendly fire.",
	"Friends who eat all the snacks.",
	"Friends with benefits.",
	"Frolicking.",
	"Full frontal nudity.",
	"Funky fresh rhymes.",
	"Gandalf.",
	"Gary Coleman.",
	"Gayed.",
	"Geese.",
	"Genetically engineered super-soldiers.",
	"Genghis Khan.",
	"Genital piercings.",
	"George Clooney's musk.",
	"German dungeon porn.",
	"Getting abducted by aliens.",
	"Getting drunk on mouthwash.",
	"Getting in her pants.",
	"Getting naked and watching Nickelodeon.",
	"Getting really high.",
	"Getting so angry that you pop a boner.",
	"Ghosts.",
	"Girls.",
	"Giving 110%.",
	"Gladys Knight and the Pips.",
	"Glenn Beck being right about everything.",
	"Glenn Beck catching bird flu.",
	"Global warming.",
	"Gloryholes.",
	"Goats eating cans.",
	"Goblins.",
	"God.",
	"GoGurt.",
	"Golden showers.",
	"Good grammar.",
	"Grandma.",
	"Grandpa's ashes.",
	"Graphic violence, adult language, and some sexual content.",
	"Grave robbing.",
	"Guys who don't call.",
	"Half-assed foreplay.",
	"Harry Potter erotica.",
	"Heartwarming orphans.",
	"Her Royal Highness, Queen Elizabeth II.",
	"Heteronormativity.",
	"Hillary Clinton's death stare.",
	"Hipsters.",
	"Historical revisionism.",
	"Home video of Oprah sobbing into a Lean Cuisine®.",
	"Homeless people.",
	"Hope.",
	"Hormone injections.",
	"Horrifying laser hair removal accidents.",
	"Horse meat.",
	"Hot cheese.",
	"Hot people.",
	"Hot Pockets®.",
	"Hulk Hogan.",
	"Hurricane Katrina.",
	"Impotence.",
	"Improvised explosive devices.",
	"Incest.",
	"Inappropriate yodeling.",
	"Industrial accidents.",
	"Inserting a Mason jar into my anus.",
	"Invading Poland.",
	"Italians.",
	"Itchy pussy.",
	"J.D. Power and his associates.",
	"Jade Goody's cancerous remains.",
	"Japanese rope technique.",
	"Jean-Claude Van Damme.",
	"Jeff Goldblum.",
	"Jerking off into a pool of children's tears.",
	"Jew-fros."
]
